services:
  db:
    container_name: deployerx-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - connection_deployer

  deployerx-api:
    container_name: deployerx-api
    restart: unless-stopped
    depends_on:
      - db
    build: .
    ports:
      - "3333:3333"
    env_file:
      - .env.app
    networks:
      - connection_deployer

volumes:
  db_data:

networks:
  connection_deployer:
    driver: bridge